// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEc5fKC1V04SDoOO7jw-wMkKFvtl6U9qU',
    appId: '1:853305782122:web:54d0d3f452b0cdfd16bf13',
    messagingSenderId: '853305782122',
    projectId: 'everesports-c2dfe',
    authDomain: 'everesports-c2dfe.firebaseapp.com',
    storageBucket: 'everesports-c2dfe.firebasestorage.app',
    measurementId: 'G-QM53Y8FHCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbUjNp-cQoYiBmXkwfCkogGR9jrRV8XIw',
    appId: '1:853305782122:android:19eb125ffbea97dc16bf13',
    messagingSenderId: '853305782122',
    projectId: 'everesports-c2dfe',
    storageBucket: 'everesports-c2dfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbd8urzzvzVYmRizDVJ3PZ9olcn9i7YfA',
    appId: '1:853305782122:ios:7ec3ce410a832f0c16bf13',
    messagingSenderId: '853305782122',
    projectId: 'everesports-c2dfe',
    storageBucket: 'everesports-c2dfe.firebasestorage.app',
    iosBundleId: 'com.example.everesportsFireBeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbd8urzzvzVYmRizDVJ3PZ9olcn9i7YfA',
    appId: '1:853305782122:ios:7ec3ce410a832f0c16bf13',
    messagingSenderId: '853305782122',
    projectId: 'everesports-c2dfe',
    storageBucket: 'everesports-c2dfe.firebasestorage.app',
    iosBundleId: 'com.example.everesportsFireBeta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEc5fKC1V04SDoOO7jw-wMkKFvtl6U9qU',
    appId: '1:853305782122:web:0371bc99f64f522d16bf13',
    messagingSenderId: '853305782122',
    projectId: 'everesports-c2dfe',
    authDomain: 'everesports-c2dfe.firebaseapp.com',
    storageBucket: 'everesports-c2dfe.firebasestorage.app',
    measurementId: 'G-VJBDNYMKCQ',
  );
}
